// Fish database — 73 species + 5 trash items
// Populated in Build Order Step 2 from docs/scoring-prompt.md (Part 6 species tables)
//
// Each fish needs:
//   - id, species, scientificName
//   - habitats: pond | river_lake | coastal | reef_open_sea | deep_ocean | mountain_stream | volcanic_arctic
//   - sizeRange: tiny | small | medium | large | trophy
//   - topics: casual | creative | technical | research | philosophical | playful | practical
//   - emoji, description, flavorTexts (2-3, witty and concise)
//
// Special rules:
//   - Coelacanth, Giant Squid, Horseshoe Crab: catchAndRelease: true
//   - Trash threshold: total <= 4 returns a trashItems entry
//
// See: docs/phase1-spec.md Section 11 for tone/structure examples
// See: docs/scoring-prompt.md Part 6 for full species tables

import type { Fish, CatchResult } from "./types";

export const fishDatabase: Fish[] = [
  // === POND (Depth 1) — 12 Species ===
  {
    id: "goldfish",
    species: "Goldfish",
    scientificName: "Carassius auratus",
    habitats: ["pond"],
    sizeRange: ["tiny", "small"],
    topics: ["casual", "playful"],
    emoji: "🐟",
    description:
      "The first fish most people ever meet. Cheerful, familiar, surprisingly hardy.",
    flavorTexts: [
      "A classic. No shame in a goldfish.",
      "It stares at you with zero judgment.",
      "Your starter fish. Everyone starts here.",
    ],
  },
  {
    id: "koi",
    species: "Koi",
    scientificName: "Cyprinus rubrofuscus",
    habitats: ["pond"],
    sizeRange: ["small", "medium", "large"],
    topics: ["creative", "philosophical"],
    emoji: "🎏",
    description: "Living art. Bred for beauty over centuries, each one unique.",
    flavorTexts: [
      "This one's worth more than your rent.",
      "Centuries of selective breeding, in your hands.",
      "A painting that swims.",
    ],
  },
  {
    id: "bluegill",
    species: "Bluegill",
    scientificName: "Lepomis macrochirus",
    habitats: ["pond"],
    sizeRange: ["tiny", "small", "medium"],
    topics: ["casual", "practical"],
    emoji: "🐠",
    description: "The reliable panfish. Every kid's first real catch.",
    flavorTexts: [
      "Generations of childhoods, one fish at a time.",
      "Not glamorous. Absolutely essential.",
      "The fish that made you believe fishing was easy.",
    ],
  },
  {
    id: "common_carp",
    species: "Common Carp",
    scientificName: "Cyprinus carpio",
    habitats: ["pond"],
    sizeRange: ["medium", "large", "trophy"],
    topics: ["practical", "research"],
    emoji: "🐡",
    description: "Underestimated and overprepared. Thrives anywhere.",
    flavorTexts: [
      "Introduced everywhere. Regretted everywhere. Still thriving.",
      "The carp doesn't care what you think of it.",
      "Europe considers it a delicacy. America considers it a pest. The carp considers itself fine.",
    ],
  },
  {
    id: "channel_catfish",
    species: "Channel Catfish",
    scientificName: "Ictalurus punctatus",
    habitats: ["pond"],
    sizeRange: ["small", "medium", "large"],
    topics: ["practical", "casual"],
    emoji: "🐟",
    description:
      "Bottom-feeder with a big appetite. Prefers to work the night shift.",
    flavorTexts: [
      "It found your bait by smell alone. In the dark. Impressive.",
      "The catfish has no enemies — only future dinners.",
      "Whiskers, attitude, and an incredible sense of smell.",
    ],
  },
  {
    id: "guppy",
    species: "Guppy",
    scientificName: "Poecilia reticulata",
    habitats: ["pond"],
    sizeRange: ["tiny"],
    topics: ["casual", "playful"],
    emoji: "🐠",
    description:
      "Tiny, colorful, endlessly reproducing. The starter fish of the hobby world.",
    flavorTexts: [
      "You blinked and there are forty more of them.",
      "The guppy's life goal: reproduce before something eats it.",
      "Small, bright, and absolutely everywhere.",
    ],
  },
  {
    id: "mosquitofish",
    species: "Mosquitofish",
    scientificName: "Gambusia affinis",
    habitats: ["pond"],
    sizeRange: ["tiny"],
    topics: ["technical", "practical"],
    emoji: "🐟",
    description:
      "Tiny but purposeful. Deployed worldwide as biological pest control.",
    flavorTexts: [
      "Weaponized by governments to fight malaria. Tiny hero.",
      "The most deliberately spread fish on Earth. For a good reason.",
      "It eats mosquito larvae. You're welcome.",
    ],
  },
  {
    id: "bullfrog",
    species: "Bullfrog",
    scientificName: "Lithobates catesbeianus",
    habitats: ["pond"],
    sizeRange: ["small"],
    topics: ["playful", "casual"],
    emoji: "🐸",
    description: "Not a fish. Doesn't care. Showed up anyway.",
    flavorTexts: [
      "Technically not what you were fishing for. Equally valid.",
      "It stared at your bobber for ten minutes before grabbing it.",
      "The pond's most self-confident non-fish.",
    ],
  },
  {
    id: "crawdad",
    species: "Crawdad",
    scientificName: "Procambarus clarkii",
    habitats: ["pond"],
    sizeRange: ["tiny", "small"],
    topics: ["playful", "practical"],
    emoji: "🦞",
    description: "Little freshwater lobster with big attitude. Pinches back.",
    flavorTexts: [
      "Proportionally, the most aggressive creature in the pond.",
      "It's essentially a tiny angry lobster. Respect it.",
      "In Louisiana they'd boil you for this. High praise.",
    ],
  },
  {
    id: "betta",
    species: "Betta",
    scientificName: "Betta splendens",
    habitats: ["pond"],
    sizeRange: ["tiny"],
    topics: ["creative", "philosophical"],
    emoji: "🐡",
    description: "Solitary and stunning. Flares at its own reflection.",
    flavorTexts: [
      "A fish that fights itself for fun. We get it.",
      "The most dramatic animal you can own for under ten dollars.",
      "Beautiful, territorial, and completely convinced it's the main character.",
    ],
  },
  {
    id: "axolotl",
    species: "Axolotl",
    scientificName: "Ambystoma mexicanum",
    habitats: ["pond"],
    sizeRange: ["small"],
    topics: ["creative", "research"],
    emoji: "🦎",
    description:
      "The smiling salamander that never grows up. Can regenerate its own brain.",
    flavorTexts: [
      "Critically endangered in the wild. Thriving in your aquarium.",
      "It can regrow its own heart. Science is still baffled.",
      "Technically an amphibian. Practically a miracle.",
    ],
  },
  {
    id: "snapping_turtle",
    species: "Snapping Turtle",
    scientificName: "Chelydra serpentina",
    habitats: ["pond"],
    sizeRange: ["medium", "large"],
    topics: ["philosophical", "playful"],
    emoji: "🐢",
    description:
      "Ancient, patient, and absolutely will bite. A living fossil with opinions.",
    flavorTexts: [
      "It was here before you and will be here after.",
      "The pond's elder. Best approached with caution and respect.",
      "Has survived everything the planet has thrown at it. Still grumpy.",
    ],
  },

  // === RIVER & LAKE (Depth 2) — 14 Species ===
  {
    id: "largemouth_bass",
    species: "Largemouth Bass",
    scientificName: "Micropterus salmoides",
    habitats: ["river_lake"],
    sizeRange: ["small", "medium", "large"],
    topics: ["casual", "practical"],
    emoji: "🐟",
    description:
      "The king of freshwater sport fishing. Explosive strikes, big ego.",
    flavorTexts: [
      "Hit your lure with all the subtlety of a freight train.",
      "Entire industries exist because of this fish's bad temper.",
      "It didn't want to be caught. It just couldn't help itself.",
    ],
  },
  {
    id: "rainbow_trout",
    species: "Rainbow Trout",
    scientificName: "Oncorhynchus mykiss",
    habitats: ["river_lake"],
    sizeRange: ["small", "medium", "large"],
    topics: ["casual", "creative"],
    emoji: "🌈",
    description: "A flash of color in cold, clear water. The postcard fish.",
    flavorTexts: [
      "Every fishing magazine cover, forever.",
      "It lives in the prettiest places you'll ever fish.",
      "Iridescent, fast, and worth waking up at 4am for.",
    ],
  },
  {
    id: "walleye",
    species: "Walleye",
    scientificName: "Sander vitreus",
    habitats: ["river_lake"],
    sizeRange: ["medium", "large"],
    topics: ["practical", "research"],
    emoji: "🐟",
    description:
      "Glassy-eyed predator of the northern lakes. Prized at the dinner table.",
    flavorTexts: [
      "Those reflective eyes see better in the dark than you ever will.",
      "The northern angler's fish. No argument accepted.",
      "Hard to find, worth finding.",
    ],
  },
  {
    id: "northern_pike",
    species: "Northern Pike",
    scientificName: "Esox lucius",
    habitats: ["river_lake"],
    sizeRange: ["medium", "large", "trophy"],
    topics: ["technical", "research"],
    emoji: "🦷",
    description: "The freshwater torpedo. All teeth and ambition.",
    flavorTexts: [
      "It didn't strike your lure. It executed a calculated attack.",
      "Every other fish in the lake is a potential snack.",
      "Nature's blueprint for pure predatory efficiency.",
    ],
  },
  {
    id: "yellow_perch",
    species: "Yellow Perch",
    scientificName: "Perca flavescens",
    habitats: ["river_lake"],
    sizeRange: ["tiny", "small", "medium"],
    topics: ["casual", "practical"],
    emoji: "🐠",
    description: "Striped, scrappy, and delicious. The everyman's fish.",
    flavorTexts: [
      "Underrated on the plate. Overrated at nothing.",
      "Schools of them. Catch one, catch thirty.",
      "The fish that made ice fishing worthwhile.",
    ],
  },
  {
    id: "smallmouth_bass",
    species: "Smallmouth Bass",
    scientificName: "Micropterus dolomieu",
    habitats: ["river_lake"],
    sizeRange: ["small", "medium", "large"],
    topics: ["technical", "practical"],
    emoji: "🐟",
    description:
      "Fights harder than its largemouth cousin. Pound for pound, a champion.",
    flavorTexts: [
      "Size for size, the hardest-fighting fish in fresh water.",
      "It will leap. Multiple times. You will respect it.",
      "The fish that made you upgrade your gear.",
    ],
  },
  {
    id: "lake_sturgeon",
    species: "Lake Sturgeon",
    scientificName: "Acipenser fulvescens",
    habitats: ["river_lake"],
    sizeRange: ["large", "trophy"],
    topics: ["philosophical", "research"],
    emoji: "🦈",
    description: "A dinosaur that never left. Can live over 100 years.",
    flavorTexts: [
      "This fish might be older than your grandparents.",
      "Armored, ancient, and completely unbothered by modernity.",
      "It survived the ice age. It'll survive you too.",
    ],
  },
  {
    id: "longnose_gar",
    species: "Longnose Gar",
    scientificName: "Lepisosteus osseus",
    habitats: ["river_lake"],
    sizeRange: ["medium", "large"],
    topics: ["research", "philosophical"],
    emoji: "🐊",
    description: "Armored in ganoid scales. Unchanged for 100 million years.",
    flavorTexts: [
      "Evolution looked at this design and said 'perfect, keep it.'",
      "That needle snout is older than the Rockies.",
      "It breathes air when the water runs low. Backup plans are good.",
    ],
  },
  {
    id: "crappie",
    species: "Crappie",
    scientificName: "Pomoxis spp.",
    habitats: ["river_lake"],
    sizeRange: ["tiny", "small", "medium"],
    topics: ["casual", "playful"],
    emoji: "🐟",
    description:
      "Great name, better taste. Schooling fish that rewards patience.",
    flavorTexts: [
      "You will spend ten minutes explaining to someone how to say this.",
      "Pronounced 'CRAW-pee.' The fish is aware of the other pronunciation.",
      "Schools deep. Tastes great. Name is a gift.",
    ],
  },
  {
    id: "muskellunge",
    species: "Muskellunge",
    scientificName: "Esox masquinongy",
    habitats: ["river_lake"],
    sizeRange: ["large", "trophy"],
    topics: ["technical", "research"],
    emoji: "🐍",
    description:
      "'The fish of 10,000 casts.' Legendary among freshwater anglers.",
    flavorTexts: [
      "You may fish for it your entire life and never catch one. That's the deal.",
      "It followed your lure to the boat and turned away. Again.",
      "The muskie owns you, not the other way around.",
    ],
  },
  {
    id: "paddlefish",
    species: "Paddlefish",
    scientificName: "Polyodon spathula",
    habitats: ["river_lake"],
    sizeRange: ["large", "trophy"],
    topics: ["philosophical", "creative"],
    emoji: "🪈",
    description:
      "Filter-feeding fossil with a paddle for a face. Gentle giant of muddy rivers.",
    flavorTexts: [
      "That rostrum is half its body length. Nobody asked for that. It happened anyway.",
      "Filter-feeds like a whale shark, looks like a spaceship.",
      "One of the strangest fish in North America, hiding in plain sight.",
    ],
  },
  {
    id: "brook_trout",
    species: "Brook Trout",
    scientificName: "Salvelinus fontinalis",
    habitats: ["river_lake"],
    sizeRange: ["tiny", "small", "medium"],
    topics: ["creative", "casual"],
    emoji: "✨",
    description:
      "Jewel of cold streams. Painted by nature with impossible colors.",
    flavorTexts: [
      "The most beautiful fish in North America. Not up for debate.",
      "Orange belly, worm-patterned back, red dots with blue halos. Overkill.",
      "If a painter made this up, you'd say it was unrealistic.",
    ],
  },
  {
    id: "bowfin",
    species: "Bowfin",
    scientificName: "Amia calva",
    habitats: ["river_lake"],
    sizeRange: ["medium", "large"],
    topics: ["research", "technical"],
    emoji: "🐟",
    description: "The last of its order. A living fossil that breathes air.",
    flavorTexts: [
      "Its entire taxonomic order contains just this one fish.",
      "Can breathe air using its swim bladder. A useful backup.",
      "Anglers call it a trash fish. Scientists call it irreplaceable.",
    ],
  },
  {
    id: "freshwater_drum",
    species: "Freshwater Drum",
    scientificName: "Aplodinotus grunniens",
    habitats: ["river_lake"],
    sizeRange: ["medium", "large"],
    topics: ["playful", "practical"],
    emoji: "🥁",
    description:
      "Makes a drumming sound with its swim bladder. The musician of the river.",
    flavorTexts: [
      "It's literally making music right now. In your hands.",
      "The only fish with a built-in percussion section.",
      "Grunts. Fights. Tastes fine. Has a brand.",
    ],
  },

  // === COASTAL WATERS (Depth 3) — 12 Species ===
  {
    id: "red_drum",
    species: "Red Drum",
    scientificName: "Sciaenops ocellatus",
    habitats: ["coastal"],
    sizeRange: ["medium", "large", "trophy"],
    topics: ["practical", "casual"],
    emoji: "🔴",
    description:
      "Bronze powerhouse of the shallows. Also called redfish. A Southern staple.",
    flavorTexts: [
      "That black spot near the tail? Predators aim there. They miss.",
      "Blackened redfish launched a thousand Cajun restaurants.",
      "The shallow-water brawler with impeccable table manners.",
    ],
  },
  {
    id: "flounder",
    species: "Flounder",
    scientificName: "Paralichthys spp.",
    habitats: ["coastal"],
    sizeRange: ["small", "medium", "large"],
    topics: ["technical", "practical"],
    emoji: "🫓",
    description:
      "Both eyes on one side. Lies flat and waits. Master of camouflage and patience.",
    flavorTexts: [
      "Starts life with eyes on both sides. Decides that's too normal.",
      "It is the seafloor, as far as anything else is concerned.",
      "Patience as a survival strategy. Highly effective.",
    ],
  },
  {
    id: "snook",
    species: "Snook",
    scientificName: "Centropomus undecimalis",
    habitats: ["coastal"],
    sizeRange: ["medium", "large"],
    topics: ["creative", "casual"],
    emoji: "🐟",
    description:
      "Sleek, silver, and explosive. The ghost of the mangroves.",
    flavorTexts: [
      "You saw it. It saw you. It left. Better luck next time.",
      "Haunts mangrove edges like something with personal secrets.",
      "Eats plugs, spooks at shadows, tastes incredible.",
    ],
  },
  {
    id: "tarpon",
    species: "Tarpon",
    scientificName: "Megalops atlanticus",
    habitats: ["coastal"],
    sizeRange: ["large", "trophy"],
    topics: ["research", "creative"],
    emoji: "⚡",
    description:
      "The Silver King. Leaps six feet out of the water. Been around since the dinosaurs.",
    flavorTexts: [
      "It will jump four times and throw your hook twice. Worth it.",
      "100 million years of evolution made the perfect leaping machine.",
      "No other fish makes grown anglers cry like this one.",
    ],
  },
  {
    id: "bonefish",
    species: "Bonefish",
    scientificName: "Albula vulpes",
    habitats: ["coastal"],
    sizeRange: ["small", "medium"],
    topics: ["technical", "practical"],
    emoji: "🦴",
    description:
      "The 'gray ghost' of the flats. Fly fishing's ultimate challenge.",
    flavorTexts: [
      "It sees your shadow. It's already gone.",
      "Spooks at anything. Catches only the patient and the precise.",
      "The flats fish that made fly fishing a lifestyle.",
    ],
  },
  {
    id: "sheepshead",
    species: "Sheepshead",
    scientificName: "Archosargus probatocephalus",
    habitats: ["coastal"],
    sizeRange: ["small", "medium"],
    topics: ["playful", "casual"],
    emoji: "🦷",
    description: "Has human-looking teeth. Seriously. Google it.",
    flavorTexts: [
      "You made eye contact with a fish and felt uncomfortable. Valid.",
      "Those teeth are for crushing barnacles. Still unsettling.",
      "The most unnerving smile in the estuary.",
    ],
  },
  {
    id: "mangrove_snapper",
    species: "Mangrove Snapper",
    scientificName: "Lutjanus griseus",
    habitats: ["coastal"],
    sizeRange: ["small", "medium"],
    topics: ["practical", "casual"],
    emoji: "🐟",
    description:
      "Smart, cautious, and delicious. The survivor of the estuary.",
    flavorTexts: [
      "It will inspect your bait and decline. Repeatedly.",
      "Knows every trick. Respects none of them.",
      "The estuary's most finicky, most rewarding resident.",
    ],
  },
  {
    id: "blue_crab",
    species: "Blue Crab",
    scientificName: "Callinectes sapidus",
    habitats: ["coastal"],
    sizeRange: ["tiny", "small"],
    topics: ["playful", "practical"],
    emoji: "🦀",
    description:
      "Feisty, beautiful, and the foundation of a hundred regional cuisines.",
    flavorTexts: [
      "It will absolutely rearrange your fingers if given the chance.",
      "Maryland built an identity around this crab's existence.",
      "Callinectes sapidus means 'beautiful savory swimmer.' Named correctly.",
    ],
  },
  {
    id: "horseshoe_crab",
    species: "Horseshoe Crab",
    scientificName: "Limulus polyphemus",
    habitats: ["coastal"],
    sizeRange: ["small", "medium"],
    topics: ["philosophical", "research"],
    emoji: "🔵",
    description:
      "Not a crab. 450 million years old. Its blue blood saves human lives.",
    flavorTexts: [
      "Every vaccine you've ever taken was tested using its blue blood.",
      "It predates the dinosaurs by 200 million years and is still at it.",
      "Ancient beyond comprehension, and still showing up every spring to breed.",
    ],
    catchAndRelease: true,
  },
  {
    id: "stingray",
    species: "Stingray",
    scientificName: "Dasyatis americana",
    habitats: ["coastal"],
    sizeRange: ["medium", "large"],
    topics: ["creative", "philosophical"],
    emoji: "🪁",
    description: "Graceful underwater flier. Gentle unless you step on it.",
    flavorTexts: [
      "Shuffle your feet in the shallows. This is why.",
      "From above, the most elegant thing in the water. From below, same.",
      "Completely peaceful until it isn't. Sound advice: watch your step.",
    ],
  },
  {
    id: "spotted_seatrout",
    species: "Spotted Seatrout",
    scientificName: "Cynoscion nebulosus",
    habitats: ["coastal"],
    sizeRange: ["small", "medium", "large"],
    topics: ["casual", "practical"],
    emoji: "✨",
    description:
      "Speckled beauty of the grass flats. Reliable, tasty, and fun to catch.",
    flavorTexts: [
      "The Gulf Coast's favorite fish. No qualifiers needed.",
      "Hits topwater lures with the enthusiasm of someone who really means it.",
      "Beautiful on the flats, beautiful on the plate.",
    ],
  },
  {
    id: "remora",
    species: "Remora",
    scientificName: "Echeneidae family",
    habitats: ["coastal"],
    sizeRange: ["small", "medium"],
    topics: ["playful", "philosophical"],
    emoji: "🪝",
    description:
      "The ultimate hitchhiker. Suctions onto sharks and rides for free. Living proof that laziness is a survival strategy.",
    flavorTexts: [
      "Evolved a suction disc on its head specifically to not have to swim.",
      "Works zero hours per week. Eats regularly. No regrets.",
      "The marine world's most successful freeloader.",
    ],
  },

  // === REEF & OPEN SEA (Depth 4) — 14 Species ===
  {
    id: "clownfish",
    species: "Clownfish",
    scientificName: "Amphiprion ocellaris",
    habitats: ["reef_open_sea"],
    sizeRange: ["tiny"],
    topics: ["playful", "creative"],
    emoji: "🤡",
    description:
      "Lives rent-free inside a venomous anemone. Famous for getting lost.",
    flavorTexts: [
      "The anemone would kill anything else. For this fish, it's home.",
      "After that movie, every child wanted one. Every aquarium suffered.",
      "It knows exactly where it lives. Stop asking.",
    ],
  },
  {
    id: "parrotfish",
    species: "Parrotfish",
    scientificName: "Scaridae family",
    habitats: ["reef_open_sea"],
    sizeRange: ["small", "medium"],
    topics: ["creative", "playful"],
    emoji: "🦜",
    description: "Eats coral, poops sand. Literally creates tropical beaches.",
    flavorTexts: [
      "That white sand beach? Parrotfish droppings. You're welcome.",
      "Bites off chunks of coral with a beak made of fused teeth.",
      "A fish that builds islands, one bite at a time.",
    ],
  },
  {
    id: "lionfish",
    species: "Lionfish",
    scientificName: "Pterois volitans",
    habitats: ["reef_open_sea"],
    sizeRange: ["small", "medium"],
    topics: ["technical", "creative"],
    emoji: "🦁",
    description: "Stunning and invasive. Beautiful problem-causer.",
    flavorTexts: [
      "Native to the Indo-Pacific. Currently thriving in the Atlantic, uninvited.",
      "Every spine is venomous. It knows this and acts accordingly.",
      "The most photogenic ecological disaster in marine history.",
    ],
  },
  {
    id: "mahi_mahi",
    species: "Mahi-Mahi",
    scientificName: "Coryphaena hippurus",
    habitats: ["reef_open_sea"],
    sizeRange: ["medium", "large"],
    topics: ["creative", "casual"],
    emoji: "🌊",
    description:
      "The most photogenic fish in the sea. Changes color as it dies.",
    flavorTexts: [
      "Alive: electric blue and gold. Dead: dull gray. Make a choice.",
      "The offshore angler's reward for getting up before sunrise.",
      "Fast-growing, fast-eating, and absolutely stunning.",
    ],
  },
  {
    id: "bluefin_tuna",
    species: "Bluefin Tuna",
    scientificName: "Thunnus thynnus",
    habitats: ["reef_open_sea"],
    sizeRange: ["large", "trophy"],
    topics: ["research", "technical"],
    emoji: "🐟",
    description:
      "Open-ocean torpedo. Warm-blooded, insanely fast. Sells for millions at auction.",
    flavorTexts: [
      "A single fish sold for $3.1 million in Tokyo. True story.",
      "Warm-blooded, retractable fins, cruising at 40 mph. Overbuilt for this ocean.",
      "The fish that made sushi famous. Also endangered. Related.",
    ],
  },
  {
    id: "blue_marlin",
    species: "Blue Marlin",
    scientificName: "Makaira nigricans",
    habitats: ["reef_open_sea"],
    sizeRange: ["large", "trophy"],
    topics: ["research", "creative"],
    emoji: "⚔️",
    description:
      "The old man's fish. The pinnacle of sport fishing.",
    flavorTexts: [
      "Hemingway wrote a whole book about a fish just like this one.",
      "Uses that bill to stun prey. Not decorative. Very functional.",
      "The deep ocean has a boss. This is it.",
    ],
  },
  {
    id: "sailfish",
    species: "Sailfish",
    scientificName: "Istiophorus platypterus",
    habitats: ["reef_open_sea"],
    sizeRange: ["large", "trophy"],
    topics: ["creative", "technical"],
    emoji: "⛵",
    description:
      "Fastest fish in the ocean. 68 mph. That dorsal fin is pure drama.",
    flavorTexts: [
      "Raises its sail to herd baitfish. A fish with tactics.",
      "68 miles per hour. You cannot imagine how fast that is underwater.",
      "Nature spent millions of years designing the perfect predator and added a sail for flair.",
    ],
  },
  {
    id: "seahorse",
    species: "Seahorse",
    scientificName: "Hippocampus spp.",
    habitats: ["reef_open_sea"],
    sizeRange: ["tiny"],
    topics: ["creative", "philosophical"],
    emoji: "🐴",
    description: "Males get pregnant. Terrible swimmers. Absolutely iconic.",
    flavorTexts: [
      "The male carries the babies. Not a metaphor. Literally carries them.",
      "Moves by fluttering a tiny dorsal fin 35 times per second. Exhausting.",
      "Defies every expectation of what a fish is allowed to be.",
    ],
  },
  {
    id: "pufferfish",
    species: "Pufferfish",
    scientificName: "Tetraodontidae family",
    habitats: ["reef_open_sea"],
    sizeRange: ["tiny", "small"],
    topics: ["playful", "creative"],
    emoji: "🐡",
    description:
      "Inflates when scared. Contains enough toxin to kill 30 humans. Adorable.",
    flavorTexts: [
      "The toxin has no antidote. People eat it anyway. On purpose.",
      "Becomes a spiky ball when threatened. Effective. Also delightful.",
      "Fugu chefs train for years not to kill their customers. High bar.",
    ],
  },
  {
    id: "triggerfish",
    species: "Triggerfish",
    scientificName: "Balistidae family",
    habitats: ["reef_open_sea"],
    sizeRange: ["small", "medium"],
    topics: ["technical", "playful"],
    emoji: "🔫",
    description:
      "Built like a tank with a locking dorsal spine. Aggressive and smart.",
    flavorTexts: [
      "That spine locks upright and cannot be pushed down. Wedges itself into crevices. Unkillable.",
      "Will bite divers who get too close to their nests. Correctly.",
      "The reef's most territorial resident. Has opinions about your fins.",
    ],
  },
  {
    id: "moray_eel",
    species: "Moray Eel",
    scientificName: "Muraenidae family",
    habitats: ["reef_open_sea"],
    sizeRange: ["medium", "large"],
    topics: ["technical", "philosophical"],
    emoji: "🐍",
    description:
      "Has a second set of jaws inside its throat. Yes, like the Alien.",
    flavorTexts: [
      "The inner jaws shoot forward to grab prey. Scientists were surprised too.",
      "Looks menacing. Usually just hanging there breathing. Give it space.",
      "Two sets of teeth for twice the reason to keep your hands out of reef crevices.",
    ],
  },
  {
    id: "grouper",
    species: "Grouper",
    scientificName: "Epinephelus spp.",
    habitats: ["reef_open_sea"],
    sizeRange: ["medium", "large", "trophy"],
    topics: ["practical", "research"],
    emoji: "🪨",
    description:
      "Massive, patient, and dominant. The bouncer of the reef.",
    flavorTexts: [
      "Sits on the same rock for years. Knows every fish that passes.",
      "Changes sex as it grows. Starts female, ends up male. Efficient.",
      "The reef's apex ambush predator. It doesn't chase. It waits.",
    ],
  },
  {
    id: "wahoo",
    species: "Wahoo",
    scientificName: "Acanthocybium solandri",
    habitats: ["reef_open_sea"],
    sizeRange: ["medium", "large"],
    topics: ["technical", "practical"],
    emoji: "⚡",
    description:
      "Sleek, fast, and razor-toothed. The speedster of deep trolling.",
    flavorTexts: [
      "Those teeth can sever a fishing line like scissors through paper.",
      "60 mph in the open ocean. Your lure never stood a chance.",
      "Built for one thing: going faster than everything else and eating it.",
    ],
  },
  {
    id: "ocean_sunfish",
    species: "Ocean Sunfish",
    scientificName: "Mola mola",
    habitats: ["reef_open_sea"],
    sizeRange: ["large", "trophy"],
    topics: ["playful", "philosophical"],
    emoji: "☀️",
    description:
      "The world's heaviest bony fish. Looks like God forgot to finish drawing it. Eats jellyfish and vibes.",
    flavorTexts: [
      "Weighs up to 5,000 pounds. Has no tail. Doesn't need one.",
      "Basks on its side at the surface to warm up after deep dives. Pure commitment.",
      "The universe made something this large and gave it jellyfish for enemies.",
    ],
  },

  // === DEEP OCEAN (Depth 5) — 11 Species ===
  {
    id: "anglerfish",
    species: "Anglerfish",
    scientificName: "Lophiiformes order",
    habitats: ["deep_ocean"],
    sizeRange: ["small", "medium"],
    topics: ["technical", "creative"],
    emoji: "🎣",
    description:
      "Dangles a bioluminescent lure in total darkness. The original catfisher.",
    flavorTexts: [
      "Invented the fishing rod 100 million years before humans did.",
      "The male fuses to the female's body permanently. Romance, deep-sea style.",
      "A light in the darkness that is absolutely not safe to approach.",
    ],
  },
  {
    id: "blobfish",
    species: "Blobfish",
    scientificName: "Psychrolutes marcidus",
    habitats: ["deep_ocean"],
    sizeRange: ["small"],
    topics: ["playful", "casual"],
    emoji: "😞",
    description:
      "Looks normal at depth. Looks sad at the surface. Unfairly famous.",
    flavorTexts: [
      "That sad blob face? Decompression damage from being brought up. It's fine at home.",
      "Voted ugliest animal on Earth. It was fine until humans showed up.",
      "Completely adapted to crushing pressure. Also: relatable.",
    ],
  },
  {
    id: "giant_oarfish",
    species: "Giant Oarfish",
    scientificName: "Regalecus glesne",
    habitats: ["deep_ocean"],
    sizeRange: ["trophy"],
    topics: ["creative", "philosophical"],
    emoji: "🐉",
    description:
      "The sea serpent of legend. Up to 36 feet long. Almost never seen alive.",
    flavorTexts: [
      "Every sea monster story ever told started with one of these washing ashore.",
      "36 feet of silver ribbon with a red mohawk. Not subtle.",
      "Lives so deep that almost everything we know about it comes from dead ones.",
    ],
  },
  {
    id: "gulper_eel",
    species: "Gulper Eel",
    scientificName: "Eurypharynx pelecanoides",
    habitats: ["deep_ocean"],
    sizeRange: ["medium"],
    topics: ["creative", "technical"],
    emoji: "👄",
    description:
      "Mouth bigger than its body. The deep sea's most impractical design.",
    flavorTexts: [
      "That jaw unhinges to engulf prey much larger than itself. Ambition.",
      "Bioluminescent tail tip dangles like bait. Recursive.",
      "Down here, a big mouth is the only survival plan.",
    ],
  },
  {
    id: "viperfish",
    species: "Viperfish",
    scientificName: "Chauliodus sloani",
    habitats: ["deep_ocean"],
    sizeRange: ["small"],
    topics: ["technical", "research"],
    emoji: "🗡️",
    description: "Needle fangs and a photophore belly. Pure nightmare fuel.",
    flavorTexts: [
      "Its fangs are so large they don't fit in its closed mouth.",
      "Photophores along its belly let it blend with faint surface light from below.",
      "Migrates hundreds of meters every night to feed. Dedicated.",
    ],
  },
  {
    id: "coelacanth",
    species: "Coelacanth",
    scientificName: "Latimeria chalumnae",
    habitats: ["deep_ocean"],
    sizeRange: ["large", "trophy"],
    topics: ["philosophical", "research"],
    emoji: "🏛️",
    description:
      "Thought extinct for 65 million years. Found alive in 1938. The Lazarus fish.",
    flavorTexts: [
      "Scientists declared it extinct. It disagreed.",
      "Its lobed fins move like legs. A preview of life's transition to land.",
      "Photographed and released — this one belongs to history.",
    ],
    catchAndRelease: true,
  },
  {
    id: "giant_squid",
    species: "Giant Squid",
    scientificName: "Architeuthis dux",
    habitats: ["deep_ocean"],
    sizeRange: ["trophy"],
    topics: ["philosophical", "creative"],
    emoji: "🦑",
    description:
      "Not technically a fish. Eyes the size of dinner plates. Fights sperm whales.",
    flavorTexts: [
      "The first live footage of one wasn't captured until 2004.",
      "Eyes 30cm wide — the largest of any animal. They need them down there.",
      "Goes to war with sperm whales. Neither always wins.",
    ],
    catchAndRelease: true,
  },
  {
    id: "lanternfish",
    species: "Lanternfish",
    scientificName: "Myctophidae family",
    habitats: ["deep_ocean"],
    sizeRange: ["tiny"],
    topics: ["technical", "research"],
    emoji: "💡",
    description:
      "The most abundant vertebrate on Earth. Bioluminescent. Nobody talks about them.",
    flavorTexts: [
      "Makes the largest migration on Earth every single night. Anonymously.",
      "By biomass, there may be more lanternfish than all other fish combined.",
      "The ocean's most important fish that you've never thought about.",
    ],
  },
  {
    id: "barreleye",
    species: "Barreleye",
    scientificName: "Macropinna microstoma",
    habitats: ["deep_ocean"],
    sizeRange: ["small"],
    topics: ["creative", "research"],
    emoji: "👁️",
    description:
      "Has a transparent head. You can see its brain. Looks straight up through its own skull.",
    flavorTexts: [
      "Those green glowing orbs inside its transparent dome? Eyes. Looking straight up.",
      "The fluid-filled dome is not its face. Its face is below that.",
      "Scientists had to observe it alive to realize the dome was even there.",
    ],
  },
  {
    id: "hagfish",
    species: "Hagfish",
    scientificName: "Myxini class",
    habitats: ["deep_ocean"],
    sizeRange: ["small", "medium"],
    topics: ["practical", "technical"],
    emoji: "🪱",
    description:
      "Jawless, boneless, produces buckets of slime. Unlovable but essential.",
    flavorTexts: [
      "Releases enough slime to fill a bucket in seconds. Defense mechanism. Works great.",
      "No jaw, no bones, no eyes that function. Still thriving for 300 million years.",
      "Feeds by burrowing into dead whales. Someone has to do it.",
    ],
  },
  {
    id: "frilled_shark",
    species: "Frilled Shark",
    scientificName: "Chlamydoselachus anguineus",
    habitats: ["deep_ocean"],
    sizeRange: ["medium", "large"],
    topics: ["philosophical", "research"],
    emoji: "🦕",
    description:
      "300 trident-shaped teeth. Living fossil from 80 million years ago. The deep's own dragon.",
    flavorTexts: [
      "Six gill slits fringed like a collar. Medieval and correct.",
      "Bends its body like a snake to strike prey. Sharks aren't supposed to do that.",
      "Almost never encountered. When it is, the encounter is unforgettable.",
    ],
  },

  // === MOUNTAIN STREAM (Special Habitat) — 5 Species ===
  {
    id: "golden_trout",
    species: "Golden Trout",
    scientificName: "Oncorhynchus aguabonita",
    habitats: ["mountain_stream"],
    sizeRange: ["small", "medium"],
    topics: ["practical", "research"],
    emoji: "🏔️",
    description:
      "California's state freshwater fish. Lives only above 6,800 feet. Worth the hike.",
    flavorTexts: [
      "You climbed a mountain to catch this. It was correct.",
      "Exists only where almost no one goes. That's the point.",
      "The reward for effort, altitude, and a well-placed fly.",
    ],
  },
  {
    id: "arctic_grayling",
    species: "Arctic Grayling",
    scientificName: "Thymallus arcticus",
    habitats: ["mountain_stream"],
    sizeRange: ["small", "medium"],
    topics: ["research", "technical"],
    emoji: "🏳️",
    description: "That enormous dorsal fin. Jewel of the far north.",
    flavorTexts: [
      "That sail-like fin has no practical explanation. It's just beautiful.",
      "Iridescent purple and silver. Nature showing off in a cold stream.",
      "Rises to dry flies like it's been waiting for you specifically.",
    ],
  },
  {
    id: "dolly_varden",
    species: "Dolly Varden",
    scientificName: "Salvelinus malma",
    habitats: ["mountain_stream"],
    sizeRange: ["small", "medium", "large"],
    topics: ["casual", "practical"],
    emoji: "🎀",
    description:
      "Named after a Charles Dickens character. Spotted beauty of glacier-fed streams.",
    flavorTexts: [
      "Named for a colorfully dressed Dickens character. The fish earns it.",
      "Thrives where glaciers melt. Finds cold water invigorating.",
      "Char, technically. Not a trout. Will not be correcting you in person.",
    ],
  },
  {
    id: "bull_trout",
    species: "Bull Trout",
    scientificName: "Salvelinus confluentus",
    habitats: ["mountain_stream"],
    sizeRange: ["medium", "large"],
    topics: ["technical", "research"],
    emoji: "🌡️",
    description:
      "Needs the coldest, cleanest water. A living indicator of ecosystem health.",
    flavorTexts: [
      "If bull trout are here, the watershed is healthy. Full stop.",
      "Requires water so cold and clean that almost nothing else qualifies.",
      "Its presence is the best news a river conservationist can receive.",
    ],
  },
  {
    id: "cutthroat_trout",
    species: "Cutthroat Trout",
    scientificName: "Oncorhynchus clarkii",
    habitats: ["mountain_stream"],
    sizeRange: ["small", "medium"],
    topics: ["practical", "casual"],
    emoji: "🗺️",
    description:
      "Named for the red slash under its jaw. Lewis and Clark's fish.",
    flavorTexts: [
      "Lewis and Clark ate this. You're in good historical company.",
      "That red slash looks alarming. The fish is fine.",
      "The West's native trout, in streams that have run since before the maps.",
    ],
  },

  // === VOLCANIC VENT / ARCTIC (Special Habitat) — 5 Species ===
  {
    id: "antarctic_icefish",
    species: "Antarctic Icefish",
    scientificName: "Channichthyidae family",
    habitats: ["volcanic_arctic"],
    sizeRange: ["small", "medium"],
    topics: ["research", "technical"],
    emoji: "🧊",
    description:
      "Has no hemoglobin. Clear blood. Survives by being coldblooded to the extreme.",
    flavorTexts: [
      "The only vertebrate with no hemoglobin. Clear blood. No red. Just plasma.",
      "Its heart is enormous relative to its body, compensating for bloodless circulation.",
      "Evolved a solution to a problem nothing else even has.",
    ],
  },
  {
    id: "pompeii_worm",
    species: "Pompeii Worm",
    scientificName: "Alvinella pompejana",
    habitats: ["volcanic_arctic"],
    sizeRange: ["tiny"],
    topics: ["technical", "research"],
    emoji: "🌋",
    description:
      "Lives at 176°F on hydrothermal vents. Most heat-tolerant animal on Earth. Not a fish. Doesn't care.",
    flavorTexts: [
      "Its back end sits in 176°F water. Its head is in the 'cool' zone at 72°F.",
      "Named after Pompeii. Lives the life Pompeians did not.",
      "Bacteria live on its back, possibly providing insulation. A worm wearing a coat.",
    ],
  },
  {
    id: "snailfish",
    species: "Snailfish",
    scientificName: "Pseudoliparis swirei",
    habitats: ["volcanic_arctic"],
    sizeRange: ["small"],
    topics: ["research", "philosophical"],
    emoji: "🐌",
    description:
      "Lives 8,000 meters deep in the Mariana Trench. Deepest fish ever recorded.",
    flavorTexts: [
      "Found at 8,336 meters. Pressure there is 800 times surface level. It's fine.",
      "Pale, translucent, and the undisputed depth record holder among fish.",
      "Down where nothing should live, this fish thrives and is apparently quite common.",
    ],
  },
  {
    id: "antarctic_toothfish",
    species: "Antarctic Toothfish",
    scientificName: "Dissostichus mawsoni",
    habitats: ["volcanic_arctic"],
    sizeRange: ["large", "trophy"],
    topics: ["practical", "research"],
    emoji: "❄️",
    description:
      "Sold as 'Chilean Sea Bass.' Lives under Antarctic ice. Antifreeze in its blood.",
    flavorTexts: [
      "Renamed 'Chilean Sea Bass' for marketing. Worked brilliantly. It's neither.",
      "Antifreeze proteins in its blood prevent ice crystals from forming. Biologically remarkable.",
      "Worth a fortune. Lives where almost nothing else can. Supply and demand.",
    ],
  },
  {
    id: "yeti_crab",
    species: "Yeti Crab",
    scientificName: "Kiwa hirsuta",
    habitats: ["volcanic_arctic"],
    sizeRange: ["small"],
    topics: ["creative", "playful"],
    emoji: "🦀",
    description:
      "Hairy claws, blind, farms bacteria on its own arms. Discovered in 2005. Not a fish. Incredible anyway.",
    flavorTexts: [
      "Discovered in 2005. Named after a mythical creature. Completely justified.",
      "Those hairy claws aren't decorative — they're bacterial farms. It tends them.",
      "Blind, white, and living on a hydrothermal vent. Completely at peace with all of it.",
    ],
  },
];

export const trashItems: CatchResult[] = [
  {
    species: "Old Boot",
    habitat: "trash",
    rarity: "trash",
    sizeClass: "small",
    topic: "casual",
    scores: {
      depth: 1,
      specificity: 1,
      creativity: 1,
      clarity: 1,
      total: 4,
      topic: "casual",
    },
    flavorText: "You cast nothing and caught nothing. Well, almost nothing.",
    description: "Someone's lost boot. The ocean remembers.",
    emoji: "🥾",
  },
  {
    species: "Soggy Newspaper",
    habitat: "trash",
    rarity: "trash",
    sizeClass: "small",
    topic: "casual",
    scores: {
      depth: 1,
      specificity: 1,
      creativity: 1,
      clarity: 1,
      total: 4,
      topic: "casual",
    },
    flavorText: "Yesterday's news. Literally.",
    description: "Unreadable. Much like the prompt that caught it.",
    emoji: "📰",
  },
  {
    species: "Tin Can",
    habitat: "trash",
    rarity: "trash",
    sizeClass: "tiny",
    topic: "casual",
    scores: {
      depth: 1,
      specificity: 1,
      creativity: 1,
      clarity: 1,
      total: 4,
      topic: "casual",
    },
    flavorText: "The ocean doesn't reward bad behavior. Neither do we.",
    description: "Rusty, dented, and deeply unimpressed with your prompt.",
    emoji: "🥫",
  },
  {
    species: "Seaweed Clump",
    habitat: "trash",
    rarity: "trash",
    sizeClass: "tiny",
    topic: "casual",
    scores: {
      depth: 1,
      specificity: 1,
      creativity: 1,
      clarity: 1,
      total: 4,
      topic: "casual",
    },
    flavorText: "At least it's organic.",
    description: "Slimy, green, and vaguely disappointed.",
    emoji: "🌿",
  },
  {
    species: "Driftwood",
    habitat: "trash",
    rarity: "trash",
    sizeClass: "medium",
    topic: "casual",
    scores: {
      depth: 1,
      specificity: 1,
      creativity: 1,
      clarity: 1,
      total: 4,
      topic: "casual",
    },
    flavorText: "You've been here before. Try something new.",
    description: "Weathered, shapeless, going nowhere. Sound familiar?",
    emoji: "🪵",
  },
];
